"""
SIR PURFLUOUS - BLENDER AUTOMATION SCRIPT
==========================================
HOW TO RUN (3 options, pick one):

OPTION A - Double-click (easiest):
  Run run_blender.bat (also generated by this package)

OPTION B - PowerShell:
  & "C:\Program Files\Blender Foundation\Blender 4.x\blender.exe" `
    --background `
    --python "C:\path\to\sir_purfluous_blender.py"

OPTION C - Inside Blender manually:
  1. Open Blender
  2. Switch any panel to "Text Editor"
  3. Open this file
  4. Press "Run Script"

WHAT IT DOES:
  1. Imports sir_purfluous_v1.glb
  2. Reshapes mesh parts to older/stockier proportions
  3. Applies "Too Much to Bear" stylized materials (brown suit, aged skin)
  4. Adds subdivision + sculpt modifiers for facial detail
  5. Sets up shape keys (morph targets) for facial animation
  6. Exports sir_purfluous_v2.glb ready for mocap

REQUIREMENTS:
  - Blender 3.6 or 4.x (free at blender.org)
  - sir_purfluous_v1.glb in the same folder as this script
"""

import bpy
import math
import os

# ── CONFIG ────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
INPUT_GLB    = os.path.join(SCRIPT_DIR, "sir_purfluous_v1.glb")
OUTPUT_GLB   = os.path.join(SCRIPT_DIR, "sir_purfluous_v2.glb")

# ── STEP 1: CLEAN SCENE ───────────────────────────────────────────────────────
def clean_scene():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    for col in bpy.data.collections:
        bpy.data.collections.remove(col)
    print("[1/7] Scene cleared.")

# ── STEP 2: IMPORT GLB ────────────────────────────────────────────────────────
def import_glb():
    bpy.ops.import_scene.gltf(filepath=INPUT_GLB)
    print(f"[2/7] Imported: {INPUT_GLB}")
    print(f"      Objects in scene: {[o.name for o in bpy.context.scene.objects]}")

# ── STEP 3: RESHAPE TO SIR PURFLUOUS PROPORTIONS ─────────────────────────────
# Older gentleman: wider torso, shorter neck, rounder belly,
# heavier legs, slight forward stoop in spine
RESHAPE = {
    # mesh_name            : (scale_x, scale_y, scale_z, offset_z)
    "node_sir_torso_underlayer": (1.18, 1.05, 1.18, 0.0),   # wider torso
    "node_sir_pelvis_mesh":      (1.20, 1.0,  1.20, 0.0),   # wider hips
    "node_sir_jacket_body":      (1.18, 1.04, 1.18, 0.0),   # wider jacket
    "node_sir_lapel_l":          (1.1,  1.15, 1.0,  0.0),
    "node_sir_lapel_r":          (1.1,  1.15, 1.0,  0.0),
    "node_sir_thigh_l":          (1.15, 1.0,  1.15, 0.0),   # stockier legs
    "node_sir_thigh_r":          (1.15, 1.0,  1.15, 0.0),
    "node_sir_shin_l":           (1.10, 1.0,  1.10, 0.0),
    "node_sir_shin_r":           (1.10, 1.0,  1.10, 0.0),
    "node_sir_face_mesh":        (1.05, 0.98, 1.05, 0.0),   # slightly rounder face
    "node_sir_neck":             (1.10, 0.88, 1.10, 0.0),   # shorter thicker neck
    "node_sir_hair_cap":         (1.04, 0.90, 1.04, 0.0),   # receding / flatter top
}

def reshape_proportions():
    for obj in bpy.context.scene.objects:
        if obj.type != 'MESH':
            continue
        key = obj.name
        if key in RESHAPE:
            sx, sy, sz, oz = RESHAPE[key]
            obj.scale.x *= sx
            obj.scale.y *= sy
            obj.scale.z *= sz
            obj.location.z += oz
    print("[3/7] Proportions reshaped (stocky older gentleman).")

# ── STEP 4: APPLY MATERIALS ───────────────────────────────────────────────────
# "Too Much to Bear" style: warm brown, hand-drawn-ish feel,
# slight cel-shade via mix shader, no PBR chrome

MATERIAL_SETTINGS = {
    "skin":        {"base": (0.78, 0.58, 0.44, 1.0), "roughness": 0.85, "spec": 0.05},
    "boxer":       {"base": (0.88, 0.84, 0.76, 1.0), "roughness": 0.90, "spec": 0.02},
    "suit_brown":  {"base": (0.30, 0.18, 0.08, 1.0), "roughness": 0.80, "spec": 0.08},
    "shirt_white": {"base": (0.92, 0.89, 0.82, 1.0), "roughness": 0.88, "spec": 0.03},
    "shoe_brown":  {"base": (0.20, 0.11, 0.05, 1.0), "roughness": 0.60, "spec": 0.15},
    "belt_black":  {"base": (0.08, 0.07, 0.06, 1.0), "roughness": 0.65, "spec": 0.10},
    "hair_grey":   {"base": (0.52, 0.50, 0.50, 1.0), "roughness": 0.92, "spec": 0.02},
    "eye_iris":    {"base": (0.22, 0.32, 0.52, 1.0), "roughness": 0.10, "spec": 0.80},
    "eye_white":   {"base": (0.95, 0.92, 0.88, 1.0), "roughness": 0.20, "spec": 0.30},
    "lip":         {"base": (0.60, 0.36, 0.30, 1.0), "roughness": 0.75, "spec": 0.08},
}

def build_stylized_material(mat, settings):
    """Build a node material with a subtle toon-ish quality."""
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    # Output
    out = nodes.new("ShaderNodeOutputMaterial")
    out.location = (600, 0)

    # Principled BSDF (base)
    bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.location = (200, 0)
    bsdf.inputs["Base Color"].default_value   = settings["base"]
    bsdf.inputs["Roughness"].default_value    = settings["roughness"]
    bsdf.inputs["Specular IOR Level"].default_value = settings.get("spec", 0.05)

    # Subtle color ramp for cel edge
    ramp = nodes.new("ShaderNodeValToRGB")
    ramp.location = (-200, -100)
    ramp.color_ramp.interpolation = 'CONSTANT'
    ramp.color_ramp.elements[0].position = 0.40
    ramp.color_ramp.elements[0].color    = (0.0, 0.0, 0.0, 1.0)
    ramp.color_ramp.elements[1].position = 0.41
    ramp.color_ramp.elements[1].color    = (1.0, 1.0, 1.0, 1.0)

    # Fresnel for edge darkening
    fres = nodes.new("ShaderNodeFresnel")
    fres.location = (-400, -100)
    fres.inputs["IOR"].default_value = 1.45

    # Mix: mostly BSDF, slight edge
    mix = nodes.new("ShaderNodeMixShader")
    mix.location = (400, 0)
    mix.inputs["Fac"].default_value = 0.08   # subtle — not full toon

    links.new(fres.outputs["Fac"],      ramp.inputs["Fac"])
    links.new(bsdf.outputs["BSDF"],     mix.inputs[1])
    links.new(bsdf.outputs["BSDF"],     mix.inputs[2])  # both slots = bsdf tint only
    links.new(mix.outputs["Shader"],    out.inputs["Surface"])

def apply_materials():
    for mat in bpy.data.materials:
        if mat.name in MATERIAL_SETTINGS:
            build_stylized_material(mat, MATERIAL_SETTINGS[mat.name])
    print("[4/7] Materials applied (Too Much to Bear stylized look).")

# ── STEP 5: ADD SUBDIVISION TO FACE ──────────────────────────────────────────
def add_face_subdivision():
    face_obj = bpy.data.objects.get("node_sir_face_mesh")
    if face_obj:
        bpy.context.view_layer.objects.active = face_obj
        mod = face_obj.modifiers.new(name="Subd", type='SUBSURF')
        mod.levels         = 2   # viewport
        mod.render_levels  = 3   # render
        mod.subdivision_type = 'CATMULL_CLARK'
        # Also add a Smooth modifier for the aged-skin look
        smooth_mod = face_obj.modifiers.new(name="Smooth", type='SMOOTH')
        smooth_mod.factor     = 0.5
        smooth_mod.iterations = 3
    print("[5/7] Subdivision + smooth added to face mesh.")

# ── STEP 6: ADD SHAPE KEYS (MORPH TARGETS) FOR FACIAL ANIMATION ──────────────
SHAPE_KEYS = [
    "brow_raise_l",
    "brow_raise_r",
    "brow_furrow",
    "eye_blink_l",
    "eye_blink_r",
    "eye_squint_l",
    "eye_squint_r",
    "cheek_puff_l",
    "cheek_puff_r",
    "mouth_open",
    "mouth_smile_l",
    "mouth_smile_r",
    "mouth_frown_l",
    "mouth_frown_r",
    "jaw_open",
    "lip_upper_raise",
    "lip_lower_drop",
    "viseme_aa",    # dialogue phonemes
    "viseme_ee",
    "viseme_oo",
    "viseme_ff",
    "viseme_mm",
    "viseme_th",
]

def add_shape_keys():
    face_obj = bpy.data.objects.get("node_sir_face_mesh")
    if not face_obj:
        print("[6/7] WARNING: face mesh not found, skipping shape keys.")
        return

    bpy.context.view_layer.objects.active = face_obj
    face_obj.select_set(True)

    # Basis key first
    face_obj.shape_key_add(name="Basis", from_mix=False)

    for key_name in SHAPE_KEYS:
        sk = face_obj.shape_key_add(name=key_name, from_mix=False)
        sk.value = 0.0   # start at 0 (neutral)
        # NOTE: Real displacement per key would require sculpting.
        # These are placeholder keys with correct names for your
        # animation system to drive. A rigger/animator can then
        # sculpt each key from the Basis in Blender's Shape Keys panel.

    print(f"[6/7] {len(SHAPE_KEYS)} shape keys added to face mesh.")
    print("      Keys: " + ", ".join(SHAPE_KEYS))

# ── STEP 7: EXPORT GLB ────────────────────────────────────────────────────────
def export_glb():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.export_scene.gltf(
        filepath=OUTPUT_GLB,
        export_format='GLB',
        export_animations=False,
        export_morph=True,           # includes shape keys
        export_morph_normal=True,
        export_skins=True,
        export_apply=False,          # keep modifiers non-destructive
        use_selection=False,
    )
    size_kb = os.path.getsize(OUTPUT_GLB) // 1024
    print(f"[7/7] Exported: {OUTPUT_GLB}  ({size_kb} KB)")
    print()
    print("=" * 60)
    print("  DONE — sir_purfluous_v2.glb is ready.")
    print("  Next steps:")
    print("  - Open in Blender to sculpt shape key expressions")
    print("  - Import into Unreal Engine / Unity with mocap retarget")
    print("  - Swap outfit meshes by hiding/showing mesh nodes")
    print("=" * 60)

# ── MAIN ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    clean_scene()
    import_glb()
    reshape_proportions()
    apply_materials()
    add_face_subdivision()
    add_shape_keys()
    export_glb()
